server:
  port: 8080

spring:
  main:
      allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://203.231.146.220:3306/202303_kumoh
    username: 202303_kumoh
    password: 202303_kumoh
  mail:
     # Naver smtp server 사용
#    host: smtp.naver.com
#    port: 465
#    username: poiksungi@naver.com
#    password: 
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: false
#          auth: true
#          ssl:
#            enable: true
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: poiksungi@gmail.com #앱 비밀번호 발급받은 google 계정
    password: uqhx xrze nyuv fxjr #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
          ssl:
            protocols: TLSv1.2

#Security:
  #Key: TestKey
        #NMA8JPctFuna59f5

logging:
  level:
    root: info
    egovframework.App: info


          
URL:
  Front:
    #Yoon: 학교
      #http://172.30.77.109:5173
    #Min: 학교
      #http://172.30.77.130:5173
    #Test: 공동작업 
      http://localhost:5173
  
  Back:
    #Class: 학교
      http://172.30.74.17:8080
    #Alone: 혼자 테스트할 떄
      #http://localhost:8080